// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package myservice

// Injectors from wire.go:

func InitializeUserService() *UserService {
	user := NewUserRepository()
	userService := NewUserService(user)
	return userService
}
